<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Proto\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Proto.Message.AccessRequest</code>
 */
class AccessRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 id = 1;</code>
     */
    private $id = 0;
    /**
     * <code>string method = 2;</code>
     */
    private $method = '';
    /**
     * <code>string params = 3;</code>
     */
    private $params = '';
    /**
     * <code>uint32 snum = 4;</code>
     */
    private $snum = 0;
    /**
     * <code>uint32 fnum = 5;</code>
     */
    private $fnum = 0;
    /**
     * <code>uint32 total = 6;</code>
     */
    private $total = 0;
    /**
     * <code>uint32 cost_ms = 7;</code>
     */
    private $cost_ms = 0;

    public function __construct() {
        \GPBMetadata\Message::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>uint64 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;
    }

    /**
     * <code>string method = 2;</code>
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * <code>string method = 2;</code>
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;
    }

    /**
     * <code>string params = 3;</code>
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * <code>string params = 3;</code>
     */
    public function setParams($var)
    {
        GPBUtil::checkString($var, True);
        $this->params = $var;
    }

    /**
     * <code>uint32 snum = 4;</code>
     */
    public function getSnum()
    {
        return $this->snum;
    }

    /**
     * <code>uint32 snum = 4;</code>
     */
    public function setSnum($var)
    {
        GPBUtil::checkUint32($var);
        $this->snum = $var;
    }

    /**
     * <code>uint32 fnum = 5;</code>
     */
    public function getFnum()
    {
        return $this->fnum;
    }

    /**
     * <code>uint32 fnum = 5;</code>
     */
    public function setFnum($var)
    {
        GPBUtil::checkUint32($var);
        $this->fnum = $var;
    }

    /**
     * <code>uint32 total = 6;</code>
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * <code>uint32 total = 6;</code>
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint32($var);
        $this->total = $var;
    }

    /**
     * <code>uint32 cost_ms = 7;</code>
     */
    public function getCostMs()
    {
        return $this->cost_ms;
    }

    /**
     * <code>uint32 cost_ms = 7;</code>
     */
    public function setCostMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->cost_ms = $var;
    }

}

