<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Proto\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Proto.Message.GetEtcdAddressRequest</code>
 */
class GetEtcdAddressRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Message::initOnce();
        parent::__construct();
    }

}

