<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Proto\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Proto.Message.LoadConfigResponse</code>
 */
class LoadConfigResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.Proto.Message.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * <code>string config = 2;</code>
     */
    private $config = '';

    public function __construct() {
        \GPBMetadata\Message::initOnce();
        parent::__construct();
    }

    /**
     * <code>.Proto.Message.ResponseHeader header = 1;</code>
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * <code>.Proto.Message.ResponseHeader header = 1;</code>
     */
    public function setHeader(&$var)
    {
        GPBUtil::checkMessage($var, \Proto\Message\ResponseHeader::class);
        $this->header = $var;
    }

    /**
     * <code>string config = 2;</code>
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * <code>string config = 2;</code>
     */
    public function setConfig($var)
    {
        GPBUtil::checkString($var, True);
        $this->config = $var;
    }

}

