<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Proto\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Proto.Message.OnlineResponse</code>
 */
class OnlineResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.Proto.Message.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * <code>uint64 id = 2;</code>
     */
    private $id = 0;

    public function __construct() {
        \GPBMetadata\Message::initOnce();
        parent::__construct();
    }

    /**
     * <code>.Proto.Message.ResponseHeader header = 1;</code>
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * <code>.Proto.Message.ResponseHeader header = 1;</code>
     */
    public function setHeader(&$var)
    {
        GPBUtil::checkMessage($var, \Proto\Message\ResponseHeader::class);
        $this->header = $var;
    }

    /**
     * <code>uint64 id = 2;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>uint64 id = 2;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;
    }

}

