<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Proto\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Proto.Message.ResponseHeader</code>
 */
class ResponseHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint32 status = 1;</code>
     */
    private $status = 0;
    /**
     * <code>string error = 2;</code>
     */
    private $error = '';

    public function __construct() {
        \GPBMetadata\Message::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint32 status = 1;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <code>uint32 status = 1;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;
    }

    /**
     * <code>string error = 2;</code>
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * <code>string error = 2;</code>
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;
    }

}

