<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Proto\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Proto.Message.LogRequest</code>
 */
class LogRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 id = 1;</code>
     */
    private $id = 0;
    /**
     * <code>string tag = 2;</code>
     */
    private $tag = '';
    /**
     * <code>string content = 3;</code>
     */
    private $content = '';

    public function __construct() {
        \GPBMetadata\Message::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>uint64 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;
    }

    /**
     * <code>string tag = 2;</code>
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * <code>string tag = 2;</code>
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;
    }

    /**
     * <code>string content = 3;</code>
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * <code>string content = 3;</code>
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;
    }

}

